#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(ggplot2)
library(shinyBS)

# Define UI for application that draws a histogram
ui = fluidPage(tabsetPanel(tabPanel("Iniitial visualization",h1("Iniitial visualization"),
                                    sidebarLayout(
                                      sidebarPanel(selectInput(inputId="visualization","visualization",c("Gender"="SEX","Relationship"="MARITAL","AGE"="AGE","Distance To Clinic"="DistanceToClinic","Month"="Month","DURATION"="DURATION","Insurance"="REG.FSC.1","Schedule Provider"="SCH.PROV.CATEGORY.1")),hr(),helpText("Visualizing different Parameters")),
                                      mainPanel(imageOutput("visualization"))
                                    )),
                           tabPanel("Repeat visualization",h1("Repeat visualization"),
                                    sidebarLayout(
                                      sidebarPanel(selectInput(inputId="repeat_visualization","repeat_visualization",c("Gender"="SEX","Relationship"="MARITAL","AGE"="AGE","DistanceToClinic"="DistanceToClinic","Month"="Month","DURATION"="DURATION","Insurance"="REG.FSC.1","Scheudle Provider"="SCH.PROV.CATEGORY.1")),hr(),helpText("Visualizing different Parameters")),
                                      mainPanel(imageOutput("repeat_visualization"))
                                    )),
                           
                           tabPanel
                           ("No-show Repeat arrival",h1("Forecast no-show arrival Attendance of patients using Logistic"),sidebarLayout(sidebarPanel(sliderInput(inputId = "aGE",label = "Choose your age",value=25,min = 1,max=100),bsTooltip("aGE", "Chances of person not showing up increase when hes likely to fall under the range of 10-30","top", options = list(container = "body")),
                                                                                                                                   sliderInput(inputId = "distanceToclinic",label = "Choose distance to CLinic",value=15,min = 1,max=100),bsTooltip("distanceToclinic", "The chances of not showing up decreases with the increase in distance","top", options = list(container = "body")),
                                                                                                                                   selectInput(inputId= "sEX",label = "Choose Gender",choices = c("M"="M","F" = "F")),bsTooltip("sEX", "Chances of women notshowing up is slightly higher compared to men by 4%","top", options = list(container = "body")),
                                                                                                                                   selectInput(inputId="month",label="Month", choices = c("January"="January","February"="February","March"="March","April"="April","May"="May","June"="June","July"="July","August"="August","September"="September","October"="October","November"="November","December"="December")),bsTooltip("month", "March, May, September,October, December have a slighlty higher percentage of noshows","top", options = list(container = "body")),
                                                                                                                                   sliderInput(inputId="dURATION",label = "Appointment duration",value=25,min = 15,max=180),bsTooltip("dURATION", "Chances of person not showing up increase when he has short duration scheduled appointments","top", options = list(container = "body")),
                                                                                                                                   selectInput(inputId= "rEG_FSC_1",label="REG FSC", choices = c("Commercial"="Commercial","Indigent"="Indigent","Medicaid"="Medicaid","Medicare"="Medicare","Other"="Other")),bsTooltip("rEG_FSC_1", "Chances of person not showing up is high when he holds either Indigent or Medicaid","top", options = list(container = "body")),
                                                                                                                                   selectInput(inputId="sCH_PROV_CATEGORY_1",label = "SCH.PROV.CATEGORY.1",choices=c("RESIDENT"="RESIDENT","EPILEPSY"="EPILEPSY","GENNEUROLOGY_HEADACHE"="GENNEUROLOGY_HEADACHE","MOVEMENT DISORDERS"="MOVEMENT DISORDERS")),bsTooltip("sCH_PROV_CATEGORY_1", "Resident, Epilepsy and Gen Neurology/Headache have high chances of not showing up","top", options = list(container = "body")),
                                                                                                                                   actionButton(inputId= "no_Show_Repeat",label="Calculate probability")),
                                                                                                                                   mainPanel(verbatimTextOutput("no_show_repeat"),verbatimTextOutput("no_show_repeat_forecast")))),
                           tabPanel
                           ("Can Repeat arrival",h1("Forecast patient Attendance using Machine Learning"),sidebarLayout(sidebarPanel(sliderInput(inputId = "can_repeat_age",label = "Choose your age",value=25,min = 1,max=100),bsTooltip("can_repeat_age", "Chances of cancellation for repeated visits almost is 30% for all the age categories","top", options = list(container = "body")),
                                                                                                                                         sliderInput(inputId = "can_repeat_distanceToclinic",label = "Choose distance to CLinic",value=15,min = 1,max=100),bsTooltip("can_repeat_distanceToclinic", "Chances of person cancelling is high if the distance is in the range od 40-70 miles","top", options = list(container = "body")),
                                                                                                                                         sliderInput(inputId="can_repeat_dURATION",label = "Appointment duration",value=25,min = 15,max=180),bsTooltip("can_repeat_dURATION", "Cancellations are almost 50% when its 15 mintues","top", options = list(container = "body")),
                                                                                                                                         selectInput(inputId="can_repeat_sCH_PROV_CATEGORY_1",label = "SCH.PROV.CATEGORY.1",choices=c("RESIDENT"="RESIDENT","EPILEPSY"="EPILEPSY","GENNEUROLOGY_HEADACHE"="GENNEUROLOGY_HEADACHE","MOVEMENT DISORDERS"="MOVEMENT DISORDERS")),bsTooltip("can_repeat_sCH_PROV_CATEGORY_1", "Cancellation is close to 30% for all the factors","top", options = list(container = "body")),
                                                                                                                                        selectInput(inputId="can_repeat_MARITAL",label="Marital status", choices = c("Married"="MARRIED","SINGLE"="SINGLE","DIVORCED"="DIVORCED","WIDOWED"="WIDOWED","SEPARATED"="SEPARATED")),bsTooltip("can_repeat_MARITAL", "Close to 30% cancellation in each of the categories","top", options = list(container = "body")),
                                                                                                                                         actionButton(inputId= "can_repeat_Repeat",label="Calculate probability")),
                                                                                                                                         mainPanel(verbatimTextOutput("can_repeat"),verbatimTextOutput("can_repeat_forecast")))),
                           
                           tabPanel
                           ("Can  initial",h1("Forecast patient Attendance using Machine Learning"),sidebarLayout(sidebarPanel(sliderInput(inputId = "can_initial_age",label = "Choose your age",value=25,min = 1,max=100),bsTooltip("can_initial_age", "Slightly less in the age between 30-40 & high for more than 70 years","top", options = list(container = "body")),
                                                                                                                                     sliderInput(inputId = "can_initial_distancetoclinic",label = "Choose distance to CLinic",value=15,min = 1,max=100),bsTooltip("can_initial_distancetoclinic", "High when distance is more than 50 miles","top", options = list(container = "body")),
                                                                                                                                     sliderInput(inputId="can_initial_dURATION",label = "Appointment duration",value=25,min = 15,max=180),bsTooltip("can_initial_dURATION", "Close to 30-35% when duration is equal and more than 60 mins","top", options = list(container = "body")),
                                                                                                                                     selectInput(inputId="can_initial_month",label="Month", choices = c("January"="January","February"="February","March"="March","April"="April","May"="May","June"="June","July"="July","August"="August","September"="September","October"="October","November"="November","December"="December")),bsTooltip("can_initial_month", "Range from 27% to 35% for all the months","top", options = list(container = "body")),
                                                                                                                                     actionButton(inputId= "can_initial",label="Calculate probability")),
                                                                                                                        mainPanel(verbatimTextOutput("can_initial_init"),verbatimTextOutput("can_initial_forecast")))),
                           tabPanel
                           ("Noshow initial",h1("Forecast patient Attendance using Machine Learning"),sidebarLayout(sidebarPanel(sliderInput(inputId = "noshow_initial_age",label = "Choose your age",value=25,min = 1,max=100),bsTooltip("noshow_initial_age", "No show is high until age 50","top", options = list(container = "body")),
                                                                                                                               sliderInput(inputId = "noshow_initial_distancetoclinic",label = "Choose distance to CLinic",value=15,min = 1,max=100),bsTooltip("noshow_initial_distancetoclinic", "High when less than 10 miles and greater than 60 miles","top", options = list(container = "body")),
                                                                                                                               selectInput(inputId= "noshow_initial_sEX",label = "Choose Gender",choices = c("M"="M","F" = "F")),bsTooltip("noshow_initial_sEX", "No show is high for females","top", options = list(container = "body")),
                                                                                                                               sliderInput(inputId="noshow_initial_dURATION",label = "Appointment duration",value=25,min = 15,max=180),bsTooltip("noshow_initial_dURATION", "No show is less for 60 minutes","top", options = list(container = "body")),
                                                                                                                               selectInput(inputId= "noshow_initial_rEG_FSC_1",label="REG FSC", choices = c("Commercial"="Commercial","Indigent"="Indigent","Medicaid"="Medicaid","Medicare"="Medicare","Other"="Other")),bsTooltip("noshow_initial_rEG_FSC_1", "Indigent and medicaid its high","top", options = list(container = "body")),
                                                                                                                               selectInput(inputId="noshow_initial_month",label="Month", choices = c("January"="January","February"="February","March"="March","April"="April","May"="May","June"="June","July"="July","August"="August","September"="September","October"="October","November"="November","December"="Dece,ber")),bsTooltip("noshow_initial_month", "No show high in Jan and least in July","top", options = list(container = "body")),
                                                                                                                               selectInput(inputId="noshow_initial_MARITAL",label="Marital status", choices = c("Married"="MARRIED","SINGLE"="SINGLE","DIVORCED"="DIVORCED","WIDOWED"="WIDOWED","SEPARATED"="SEPARATED")),bsTooltip("noshow_initial_MARITAL", "No show high for separated and single","top", options = list(container = "body")),
                                                                                                                               selectInput(inputId="noshow_initial_sCH_PROV_CATEGORY_1",label = "SCH.PROV.CATEGORY.1",choices=c("RESIDENT"="RESIDENT","EPILEPSY"="EPILEPSY","GENNEUROLOGY_HEADACHE"="GENNEUROLOGY_HEADACHE","MOVEMENT DISORDERS"="MOVEMENT DISORDERS")),bsTooltip("noshow_initial_sCH_PROV_CATEGORY_1", "General Neurology/Headache and Resident","top", options = list(container = "body")),
                                                                                                                               actionButton(inputId= "noshow_initial_initial",label="Calculate probability")),
                                                                                                                  mainPanel(verbatimTextOutput("noshow_arrival_initial"),verbatimTextOutput("noshow_arrival_initial_forecast"))))
                           
                           
                           
                           
              ))
